### ISSUE TITLE
chatter bot

### ISSUE THREAD

**Issue by laeakkk** [XzaiCloud/AI-Vtuber#3]
```
ERROR: Command errored out with exit status 1:
   command: 'c:\program files\python\python.exe' 'c:\program files\python\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-icabg129\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.tuna.tsinghua.edu.cn/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0'
       cwd: None
  Complete output (65 lines):
  Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
  Collecting cymem<2.1.0,>=2.0.2
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/96/99/a5f558006387913f1a1b4af5ccae610b19ebe5498e7199c2da10e77429c8/cymem-2.0.7-cp38-cp38-win_amd64.whl (30 kB)
  Collecting Cython
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/56/3a/e59db3769dee48409c759a88b62cd605324e05d396e10af0a065adc956ad/Cython-0.29.33-py2.py3-none-any.whl (987 kB)
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2c/16/a5223c2e02e6dd908fa0c93056f612ff6af6c639cbff631a380f45279beb/murmurhash-1.0.9-cp38-cp38-win_amd64.whl (18 kB)
  Collecting preshed<2.1.0,>=2.0.1
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0b/14/c9aa735cb9c131545fc9e23031baccb87041ac9215b3d75f99e3cf18f6a3/preshed-2.0.1.tar.gz (113 kB)
  Collecting setuptools
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c3/9e/8a7ba2c9984a060daa6c6f9fff4d576b7ace3936239d6b771541eab972ed/setuptools-67.6.0-py3-none-any.whl (1.1 MB)
  Collecting thinc<7.1.0,>=7.0.8
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/92/39/ea2a3d5b87fd52fc865fd1ceb7b91dca1f85e227d53e7a086d260f6bcb93/thinc-7.0.8.tar.gz (1.9 MB)
  Collecting wheel<0.33.0,>0.32.0
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl (21 kB)
  Collecting blis<0.3.0,>=0.2.1
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/59/9e/84a83616cbe5daa94909da38b780e93bf566dc2113c3dc35d7b4cad52f63/blis-0.2.4.tar.gz (1.5 MB)
  Collecting numpy>=1.7.0
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bf/8c/3d36cef521739bd481e9a5b30e5c0f9faf8b7fe7b904238368908a9d149d/numpy-1.24.2-cp38-cp38-win_amd64.whl (14.9 MB)
  Collecting plac<1.0.0,>=0.9.6
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9e/9b/62c60d2f5bc135d2aa1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl (20 kB)
  Collecting srsly<1.1.0,>=0.0.6
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/77/dc/ed06eedf66b574499d3cae5f1240e62cea1c30a8b33a57af0f53733fd48c/srsly-1.0.6-cp38-cp38-win_amd64.whl (198 kB)
  Collecting tqdm<5.0.0,>=4.10.0
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e6/02/a2cff6306177ae6bc73bc0665065de51dfb3b9db7373e122e2735faf0d97/tqdm-4.65.0-py3-none-any.whl (77 kB)
  Collecting colorama
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
  Collecting wasabi<1.1.0,>=0.0.9
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/34/74/bd566f876c2de097e75d525c2696fb9829009987a0d93a4fb3576778a0a8/wasabi-0.10.1-py3-none-any.whl (26 kB)
  Using legacy 'setup.py install' for preshed, since package 'wheel' is not installed.
  Using legacy 'setup.py install' for thinc, since package 'wheel' is not installed.
  Using legacy 'setup.py install' for blis, since package 'wheel' is not installed.
  Installing collected packages: numpy, cymem, colorama, wasabi, tqdm, srsly, preshed, plac, murmurhash, blis, wheel, thinc, setuptools, Cython
      Running setup.py install for preshed: started
      Running setup.py install for preshed: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\program files\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\khyjj\\AppData\\Local\\Temp\\pip-install-sge1p4vz\\preshed_3761555f5a7e4c5eb6dfee47e7a63518\\setup.py'"'"'; __file__='"'"'C:\\Users\\khyjj\\AppData\\Local\\Temp\\pip-install-sge1p4vz\\preshed_3761555f5a7e4c5eb6dfee47e7a63518\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\khyjj\AppData\Local\Temp\pip-record-eyd0nzn7\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-icabg129\overlay' --compile --install-headers 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-icabg129\overlay\Include\preshed'
           cwd: C:\Users\khyjj\AppData\Local\Temp\pip-install-sge1p4vz\preshed_3761555f5a7e4c5eb6dfee47e7a63518\
      Complete output (22 lines):
      WARNING: The wheel package is not available.
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\preshed
      copying preshed\about.py -> build\lib.win-amd64-3.8\preshed
      copying preshed\__init__.py -> build\lib.win-amd64-3.8\preshed
      creating build\lib.win-amd64-3.8\preshed\tests
      copying preshed\tests\test_counter.py -> build\lib.win-amd64-3.8\preshed\tests
      copying preshed\tests\test_hashing.py -> build\lib.win-amd64-3.8\preshed\tests
      copying preshed\tests\test_pop.py -> build\lib.win-amd64-3.8\preshed\tests
      copying preshed\tests\__init__.py -> build\lib.win-amd64-3.8\preshed\tests
      copying preshed\counter.pyx -> build\lib.win-amd64-3.8\preshed
      copying preshed\maps.pyx -> build\lib.win-amd64-3.8\preshed
      copying preshed\counter.pxd -> build\lib.win-amd64-3.8\preshed
      copying preshed\maps.pxd -> build\lib.win-amd64-3.8\preshed
      copying preshed\__init__.pxd -> build\lib.win-amd64-3.8\preshed
      running build_ext
      building 'preshed.maps' extension
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'c:\program files\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\khyjj\\AppData\\Local\\Temp\\pip-install-sge1p4vz\\preshed_3761555f5a7e4c5eb6dfee47e7a63518\\setup.py'"'"'; __file__='"'"'C:\\Users\\khyjj\\AppData\\Local\\Temp\\pip-install-sge1p4vz\\preshed_3761555f5a7e4c5eb6dfee47e7a63518\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\khyjj\AppData\Local\Temp\pip-record-eyd0nzn7\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-icabg129\overlay' --compile --install-headers 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-icabg129\overlay\Include\preshed' Check the logs for full command output.
  WARNING: You are using pip version 20.3.1; however, version 23.0.1 is available.
  You should consider upgrading via the 'c:\program files\python\python.exe -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python\python.exe' 'c:\program files\python\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-icabg129\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.tuna.tsinghua.edu.cn/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output.
```

**Comment by laeakkk** [comment]
ERROR: Command errored out with exit status 1:
   command: 'c:\program files\python\python.exe' 'c:\program files\python\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-gubdhqxo\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.tuna.tsinghua.edu.cn/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0'
       cwd: None
  Complete output (65 lines):
  Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
  Collecting cymem<2.1.0,>=2.0.2
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/96/99/a5f558006387913f1a1b4af5ccae610b19ebe5498e7199c2da10e77429c8/cymem-2.0.7-cp38-cp38-win_amd64.whl (30 kB)
  Collecting Cython
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/56/3a/e59db3769dee48409c759a88b62cd605324e05d396e10af0a065adc956ad/Cython-0.29.33-py2.py3-none-any.whl (987 kB)
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2c/16/a5223c2e02e6dd908fa0c93056f612ff6af6c639cbff631a380f45279beb/murmurhash-1.0.9-cp38-cp38-win_amd64.whl (18 kB)
  Collecting preshed<2.1.0,>=2.0.1
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0b/14/c9aa735cb9c131545fc9e23031baccb87041ac9215b3d75f99e3cf18f6a3/preshed-2.0.1.tar.gz (113 kB)
  Collecting setuptools
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c3/9e/8a7ba2c9984a060daa6c6f9fff4d576b7ace3936239d6b771541eab972ed/setuptools-67.6.0-py3-none-any.whl (1.1 MB)
  Collecting thinc<7.1.0,>=7.0.8
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/92/39/ea2a3d5b87fd52fc865fd1ceb7b91dca1f85e227d53e7a086d260f6bcb93/thinc-7.0.8.tar.gz (1.9 MB)
  Collecting wheel<0.33.0,>0.32.0
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl (21 kB)
  Collecting blis<0.3.0,>=0.2.1
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/59/9e/84a83616cbe5daa94909da38b780e93bf566dc2113c3dc35d7b4cad52f63/blis-0.2.4.tar.gz (1.5 MB)
  Collecting numpy>=1.7.0
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bf/8c/3d36cef521739bd481e9a5b30e5c0f9faf8b7fe7b904238368908a9d149d/numpy-1.24.2-cp38-cp38-win_amd64.whl (14.9 MB)
  Collecting plac<1.0.0,>=0.9.6
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9e/9b/62c60d2f5bc135d2aa1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl (20 kB)
  Collecting srsly<1.1.0,>=0.0.6
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/77/dc/ed06eedf66b574499d3cae5f1240e62cea1c30a8b33a57af0f53733fd48c/srsly-1.0.6-cp38-cp38-win_amd64.whl (198 kB)
  Collecting tqdm<5.0.0,>=4.10.0
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e6/02/a2cff6306177ae6bc73bc0665065de51dfb3b9db7373e122e2735faf0d97/tqdm-4.65.0-py3-none-any.whl (77 kB)
  Collecting colorama
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
  Collecting wasabi<1.1.0,>=0.0.9
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/34/74/bd566f876c2de097e75d525c2696fb9829009987a0d93a4fb3576778a0a8/wasabi-0.10.1-py3-none-any.whl (26 kB)
  Using legacy 'setup.py install' for preshed, since package 'wheel' is not installed.
  Using legacy 'setup.py install' for thinc, since package 'wheel' is not installed.
  Using legacy 'setup.py install' for blis, since package 'wheel' is not installed.
  Installing collected packages: numpy, cymem, colorama, wasabi, tqdm, srsly, preshed, plac, murmurhash, blis, wheel, thinc, setuptools, Cython
      Running setup.py install for preshed: started
      Running setup.py install for preshed: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\program files\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\khyjj\\AppData\\Local\\Temp\\pip-install-36gbbkrn\\preshed_c037800afb63439a8bfc6b493c23998c\\setup.py'"'"'; __file__='"'"'C:\\Users\\khyjj\\AppData\\Local\\Temp\\pip-install-36gbbkrn\\preshed_c037800afb63439a8bfc6b493c23998c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\khyjj\AppData\Local\Temp\pip-record-mnx9sg95\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-gubdhqxo\overlay' --compile --install-headers 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-gubdhqxo\overlay\Include\preshed'
           cwd: C:\Users\khyjj\AppData\Local\Temp\pip-install-36gbbkrn\preshed_c037800afb63439a8bfc6b493c23998c\
      Complete output (22 lines):
      WARNING: The wheel package is not available.
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\preshed
      copying preshed\about.py -> build\lib.win-amd64-3.8\preshed
      copying preshed\__init__.py -> build\lib.win-amd64-3.8\preshed
      creating build\lib.win-amd64-3.8\preshed\tests
      copying preshed\tests\test_counter.py -> build\lib.win-amd64-3.8\preshed\tests
      copying preshed\tests\test_hashing.py -> build\lib.win-amd64-3.8\preshed\tests
      copying preshed\tests\test_pop.py -> build\lib.win-amd64-3.8\preshed\tests
      copying preshed\tests\__init__.py -> build\lib.win-amd64-3.8\preshed\tests
      copying preshed\counter.pyx -> build\lib.win-amd64-3.8\preshed
      copying preshed\maps.pyx -> build\lib.win-amd64-3.8\preshed
      copying preshed\counter.pxd -> build\lib.win-amd64-3.8\preshed
      copying preshed\maps.pxd -> build\lib.win-amd64-3.8\preshed
      copying preshed\__init__.pxd -> build\lib.win-amd64-3.8\preshed
      running build_ext
      building 'preshed.maps' extension
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'c:\program files\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\khyjj\\AppData\\Local\\Temp\\pip-install-36gbbkrn\\preshed_c037800afb63439a8bfc6b493c23998c\\setup.py'"'"'; __file__='"'"'C:\\Users\\khyjj\\AppData\\Local\\Temp\\pip-install-36gbbkrn\\preshed_c037800afb63439a8bfc6b493c23998c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\khyjj\AppData\Local\Temp\pip-record-mnx9sg95\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-gubdhqxo\overlay' --compile --install-headers 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-gubdhqxo\overlay\Include\preshed' Check the logs for full command output.
  WARNING: You are using pip version 20.3.1; however, version 23.0.1 is available.
  You should consider upgrading via the 'c:\program files\python\python.exe -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python\python.exe' 'c:\program files\python\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\khyjj\AppData\Local\Temp\pip-build-env-gubdhqxo\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.tuna.tsinghua.edu.cn/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output.

**Comment by XzaiCloud** [comment]
6，用```把代码括起来吧，这样看太难受了
